### ISSUE TITLE
[FEAT] Port to BTRFS

### ISSUE THREAD

**Issue by silopolis** [iynaix/zfs.yazi#2]
Hi,

This is so freaking cool ! 😍

It would be fantastic to have the same functionality for BTRFS, and would fit so nicely with Snapper and other snapshoting tools.

TY

**Comment by iynaix** [comment]
I kinda expected this issue to surface sooner or later heh. I don't use btrfs, but I might take a look at it when I have some time.

**Comment by iynaix** [comment]
BTRFS support added. :smile: 

Renamed to time-travel.yazi since it is now more general.
