### ISSUE TITLE
Add to awesome-yazi

### ISSUE THREAD

**Issue by AnirudhG07** [iynaix/zfs.yazi#3]
Hi, cool plugin!
Would you like to add it to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi)? It would be amazing addition to the list! Please make a PR in the repo following the guidelines mentioned there. :)

Thank you!

**Comment by iynaix** [comment]
Done in https://github.com/AnirudhG07/awesome-yazi/pull/31 :rocket:

**Comment by AnirudhG07** [comment]
Thanks
